Monitoring Code for QC8
cms-gem-daq-project/gem_ops pull request #6
Opened 2019-06-20 16:33 UTC by simonepv

## Description

1- Monitoring code is independent from CMSSW and uses only python 2.7.5
2- Code cleaned. I left only parts useful for an eventual future debug
3- BitStatus.txt contains the meaning of status bits for HV A1515 and LV boards A3016 and A3016HP
4- StatusVmon904HV.py used to monitor HV system on QC8
5- StatusVmon904LV.py used to monitor LV system on QC8

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

## How Has This Been Tested?

Code has been tested comparing retrieved data with data stored on the INT2R database
The guide to use this code is on https://twiki.cern.ch/twiki/bin/view/CMS/QC8MonitoringHVLV

### Screenshots (if appropriate):

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-06-21 09:20 UTC, bdorney approved these changes

2019-06-21 09:20 UTC, bdorney commented
@jsturdy @mexanick

2019-06-21 09:24 UTC, bdorney commented
Related too: https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/222

2019-06-21 10:09 UTC, jsturdy commented on DCS_STATUS/StatusVmon904HV.py
> +		db = cx_Oracle.connect('GEM_904_COND/904CondDB@INT2R')
credentials should not be committed

2019-06-21 10:10 UTC, jsturdy commented on DCS_STATUS/StatusVmon904HV.py
> +		print "\nimonNameList", imonNameList
please uniformly use `print(str)`, you have mixed `print str` and `print(str)`

2019-06-21 10:14 UTC, jsturdy commented on DCS_STATUS/StatusVmon904HV.py
> +
consider using a python native library for this, e.g., [this](https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior) and [this](https://docs.python.org/2/library/datetime.html#datetime.datetime.strptime)

2019-06-21 10:16 UTC, jsturdy commented on DCS_STATUS/StatusVmon904HV.py
> +                Vmontg1.GetXaxis().SetTimeFormat("#splitline{%y-%m-%d}{%H:%M:%S}%F1970-01-01 00:00:00")
clean up the whitespace here (convert all `tab` characters to an appropriate number of spaces,

2019-06-21 10:17 UTC, jsturdy commented on DCS_STATUS/BitStatus.txt
> +HV boards (CAEN A1515)
is this file imported or used anywhere?
if not, its information would better be served in a user guide

2019-06-21 10:19 UTC, jsturdy requested changes
* remove secrets (from history, not just from file)
* cleanup whitespace
* utilize `python3` friendly `print()`

2019-06-21 13:54 UTC, simonepv commented
Hi Jared,

can you tell me how to remove secrets from history?
Because I have no idea on how to do it

Kind regards

Simone

Il giorno ven 21 giu 2019 alle ore 12:19 Jared Sturdy <
notifications@github.com> ha scritto:

> *@jsturdy* requested changes on this pull request.
>
>    - remove secrets (from history, not just from file)
>    - cleanup whitespace
>    - utilize python3 friendly print()
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cms-gem-daq-project/gem_ops/pull/6?email_source=notifications&email_token=AK2YXBH5ML3YDBKQZ7UHSFTP3STKBA5CNFSM4HZW7T5KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB4IKOAA#pullrequestreview-252749568>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AK2YXBBBE5V6PXRVG6GYZETP3STKBANCNFSM4HZW7T5A>
> .
>

2019-06-21 14:47 UTC, jsturdy commented
@simonepv you can try [this](https://help.github.com/en/articles/removing-sensitive-data-from-a-repository)

2019-07-31 16:48 UTC, jsturdy approved these changes

2019-07-31 22:55 UTC, merged